name: Release Obsidian Plugin

on:
    push:
        # Sequence of patterns matched against refs/tags
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
          id-token: write
          attestations: write
          contents: write

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "pnpm"

            
            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 8
              
            - name: Install Dependencies
              run: pnpm install 

            - name: Build Plugin
              run: pnpm run build

            - name: Generate artifact attestation
              uses: actions/attest-build-provenance@v4
              with:
                subject-path: |
                  main.js
                  manifest.json
                  styles.css 

            - name: Create GitHub Release
              id: create_release
              uses: softprops/action-gh-release@v4
              with:
                  tag_name: ${{ github.ref_name }}
                  name: Release ${{ github.ref_name }}
                  generate_release_notes: true
                  draft: false
                  prerelease: false

                  files: |
                      main.js
                      manifest.json
                      styles.css 
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
